version: '3.9'

services:

# Database configarartion.........................................START>
  db:
    container_name: db
    image: postgres:12
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Athish@123
      - POSTGRES_DB=dryz
    ports:
      - "5432:5432"
    networks:
      - mynetwork
# ..................................................................END>

# gunicorn configuration...........................................START>
  django_gunicorn:
    volumes:
      - static:/static
    build: 
      context: .
    ports:
      - "8000:8000"
    networks:
      - mynetwork
# ................................................................END>

# nginx configuration............................................START>
  nginx:
    build: ./nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static:/static
    ports:
      - "8080:80"
    depends_on:
      - django_gunicorn
    networks:
      - mynetwork
  # ............................................................END>

  #unomment below code if your are run locally...............START>
  # web:
  #   container_name: djangoapp
  #   build: .
  #   ports:
  #     - "8000:8000"
  #   environment:
  #     - PG_USER=username
  #     - PG_PASSWORD=password
  #     - PG_DB=myproject
  #     - PG_HOST=localhost
  #     - PG_PORT=5432
  #   depends_on:
  #     - db
# .............................................................END>




networks:
  mynetwork:
    driver: bridge
  
volumes:
  static: {}
